# Use the official LibreOffice image
FROM libreoffice/loolwsd

# Set the working directory
WORKDIR /app

# Install any additional dependencies if needed
RUN apt-get update && apt-get install -y libreoffice

# Expose the port on which LibreOffice will run
EXPOSE 5000

# Command to run LibreOffice
CMD ["loolwsd"]
