services:
  - type: web
    name: your-app
    env: python
    buildCommand:
      - apt-get update
      - apt-get install -y libreoffice xvfb
      - libreoffice --version
      - pip install -r requirements.txt
    startCommand: python app.py
